apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-agx
  namespace: default
  labels:
    app: fastapi-agx
    device: agx
    tier: agent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fastapi-agx
  template:
    metadata:
      labels:
        app: fastapi-agx
        device: agx
        tier: agent
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        kubernetes.io/hostname: agx
      containers:
      - name: fastapi-agx
        image: 10.1.10.150:30500/fastapi-agx:latest
        imagePullPolicy: Always
        command: ["/opt/venv/bin/python", "agx_app.py"]
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8888
          name: jupyter
        - containerPort: 8001
          name: llm-api
        resources:
          limits:
            # nvidia.com/gpu: 1
            memory: "2Gi"
            cpu: "1000m"
          requests:
            # nvidia.com/gpu: 1
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: DEVICE_TYPE
          value: "agx"
        - name: GPU_ENABLED
          value: "true"
        - name: FORCE_GPU_CHECKS
          value: "true"
        - name: SKIP_GPU_CHECKS
          value: "false"
        - name: POSTGRES_HOST
          value: "postgres-db"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: vmstore
          mountPath: /mnt/vmstore
        - name: agx-home
          mountPath: /home/agx
        - name: agx-workspace
          mountPath: /workspace
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: vmstore
        nfs:
          server: 10.1.10.150
          path: /export/vmstore
      - name: agx-home
        nfs:
          server: 10.1.10.150
          path: /export/vmstore/agx_home
      - name: agx-workspace
        nfs:
          server: 10.1.10.150
          path: /export/vmstore/tower_home/kubernetes/agent/agx
      tolerations:
      - key: "node-role.kubernetes.io/agent"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoExecute"
