apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-agx
  namespace: default
  labels:
    app: fastapi-agx
    device: agx
    tier: agent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fastapi-agx
  template:
    metadata:
      labels:
        app: fastapi-agx
        device: agx
        tier: agent
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        kubernetes.io/hostname: agx
      containers:
      - name: fastapi-agx
        image: 10.1.10.150:5000/fastapi-agx:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8888
          name: jupyter
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: DEVICE_TYPE
          value: "agx"
        - name: GPU_ENABLED
          value: "true"
        - name: FORCE_GPU_CHECKS
          value: "true"
        - name: POSTGRES_HOST
          value: "postgres-db"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: vmstore
          mountPath: /mnt/vmstore
        - name: agx-home
          mountPath: /home/agx
        - name: agx-config
          mountPath: /workspace/config
        - name: agx-workspace
          mountPath: /workspace
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: vmstore
        nfs:
          server: 10.1.10.150
          path: /export/vmstore
      - name: agx-home
        nfs:
          server: 10.1.10.150
          path: /export/vmstore/agx_home
      - name: agx-config
        nfs:
          server: 10.1.10.150
          path: /export/vmstore/tower_home/kubernetes/agent/agx/app/config
      - name: agx-workspace
        nfs:
          server: 10.1.10.150
          path: /export/vmstore/tower_home/kubernetes/agent/agx
      tolerations:
      - key: "node-role.kubernetes.io/agent"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoExecute"
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-agx-service
  namespace: default
  labels:
    app: fastapi-agx
    device: agx
spec:
  selector:
    app: fastapi-agx
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: jupyter
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-agx-nodeport
  namespace: default
  labels:
    app: fastapi-agx
    device: agx
spec:
  selector:
    app: fastapi-agx
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30006
    protocol: TCP
    name: http
  - port: 8888
    targetPort: 8888
    nodePort: 30007
    protocol: TCP
    name: jupyter
  type: NodePort