apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-agx
  namespace: default
  labels:
    app: fastapi-agx
    device: agx
    tier: agent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fastapi-agx
  template:
    metadata:
      labels:
        app: fastapi-agx
        device: agx
        tier: agent
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        kubernetes.io/hostname: agx
      containers:
      - name: fastapi-agx
        image: 10.1.10.150:5000/fastapi-agx:latest
        imagePullPolicy: Always
        command: ["python", "agx_app.py"]
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8888
          name: jupyter
        - containerPort: 8001
          name: llm-api
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
        env:
        - name: DEVICE_TYPE
          value: "agx"
        - name: GPU_ENABLED
          value: "true"
        - name: FORCE_GPU_CHECKS
          value: "true"
        - name: LLM_ENABLED
          value: "false"
        - name: RAG_ENABLED
          value: "false"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: vmstore
          mountPath: /mnt/vmstore
        - name: agx-home
          mountPath: /home/agx
        - name: agx-config
          mountPath: /app/app/config
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: vmstore
        nfs:
          server: 10.1.10.150
          path: /export/vmstore
      - name: agx-home
        nfs:
          server: 10.1.10.150
          path: /export/vmstore/agx_home
      - name: agx-config
        nfs:
          server: 10.1.10.150
          path: /export/vmstore/tower_home/kubernetes/agent/agx/app/config
      tolerations:
      - key: "node-role.kubernetes.io/agent"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoExecute"
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-agx-service
  namespace: default
  labels:
    app: fastapi-agx
    device: agx
spec:
  selector:
    app: fastapi-agx
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: jupyter
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: llm-api
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-agx-nodeport
  namespace: default
  labels:
    app: fastapi-agx
    device: agx
spec:
  selector:
    app: fastapi-agx
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30004
    protocol: TCP
    name: http
  - port: 8888
    targetPort: 8888
    nodePort: 30005
    protocol: TCP
    name: jupyter
  - port: 8001
    targetPort: 8001
    nodePort: 30006
    protocol: TCP
    name: llm-api
  type: NodePort