apiVersion: v1
kind: Service
metadata:
  name: postgres-db-nodeport
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432
      protocol: TCP
  selector:
    app: postgres-db
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-nodeport
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
  selector:
    app: pgadmin