apiVersion: v1
kind: Pod
metadata:
  name: manual-gpu-pod
spec:
  nodeSelector:
    kubernetes.io/hostname: spark2  # Ensure it runs on the node with GPU
  containers:
  - name: gpu-container
    image: nvidia/cuda:12.0-base  # Use a CUDA image compatible with your GPU
    command: ["nvidia-smi"]  # Or your GPU application command
    securityContext:
      privileged: true  # Required to access GPU devices
    volumeMounts:
    - name: nvidia-dev
      mountPath: /dev/nvidia0  # Mount specific GPU device
    - name: nvidia-ctl
      mountPath: /dev/nvidiactl
    - name: nvidia-uvm
      mountPath: /dev/nvidia-uvm
    - name: nvidia-modeset
      mountPath: /dev/nvidia-modeset
    - name: nvidia-libs
      mountPath: /usr/lib/x86_64-linux-gnu  # Mount NVIDIA libraries
    - name: nvidia-bin
      mountPath: /usr/bin/nvidia-smi  # Mount nvidia-smi if needed
  volumes:
  - name: nvidia-dev
    hostPath:
      path: /dev/nvidia0
  - name: nvidia-ctl
    hostPath:
      path: /dev/nvidiactl
  - name: nvidia-uvm
    hostPath:
      path: /dev/nvidia-uvm
  - name: nvidia-modeset
    hostPath:
      path: /dev/nvidia-modeset
  - name: nvidia-libs
    hostPath:
      path: /usr/lib/x86_64-linux-gnu
  - name: nvidia-bin
    hostPath:
      path: /usr/bin/nvidia-smi
  restartPolicy: Never