apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-spark1
  namespace: default
  labels:
    app: fastapi-spark1
    device: spark1
    tier: agent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fastapi-spark1
  template:
    metadata:
      labels:
        app: fastapi-spark1
        device: spark1
        tier: agent
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        kubernetes.io/hostname: spark1
      containers:
      - name: fastapi-spark1
        image: 10.1.10.150:5000/fastapi-spark1:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8888
          name: jupyter
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: DEVICE_TYPE
          value: "spark1"
        - name: GPU_ENABLED
          value: "true"
        - name: FORCE_GPU_CHECKS
          value: "true"
        - name: POSTGRES_HOST
          value: "postgres-db"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: SKIP_GPU_CHECKS
          value: "true"
        volumeMounts:
        - name: vmstore
          mountPath: /mnt/vmstore
        - name: spark1-home
          mountPath: /home/spark1
        - name: spark1-config
          mountPath: /workspace/config
        - name: spark1-workspace
          mountPath: /workspace
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: vmstore
        nfs:
          server: 10.1.10.150
          path: /export/vmstore
      - name: spark1-home
        nfs:
          server: 10.1.10.150
          path: /export/vmstore/spark1_home
      - name: spark1-config
        nfs:
          server: 10.1.10.150
          path: /export/vmstore/tower_home/kubernetes/agent/spark1/app/config
      - name: spark1-workspace
        nfs:
          server: 10.1.10.150
          path: /export/vmstore/tower_home/kubernetes/agent/spark1
      tolerations:
      - key: "node-role.kubernetes.io/agent"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoExecute"
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-spark1-service
  namespace: default
  labels:
    app: fastapi-spark1
    device: spark1
spec:
  selector:
    app: fastapi-spark1
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: jupyter
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-spark1-nodeport
  namespace: default
  labels:
    app: fastapi-spark1
    device: spark1
spec:
  selector:
    app: fastapi-spark1
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30004
    protocol: TCP
    name: http
  - port: 8888
    targetPort: 8888
    nodePort: 30005
    protocol: TCP
    name: jupyter
  type: NodePort
