apiVersion: batch/v1
kind: Job
metadata:
  name: spark1
  labels:
    app: spark1
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: spark1
    spec:
      runtimeClassName: nvidia  # Uses the NVIDIA Container Runtime
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - spark1
      containers:
      - name: spark1
        image: 192.168.1.150:30500/spark1:latest
        imagePullPolicy: "Always"
        env:
          - name: GPU_ENABLED
            value: "true"
          - name: SKIP_DB_CHECK
            value: "true"
        volumeMounts:
        - name: nvidia-dev
          mountPath: /dev/nvidia0
        - name: nvidia-ctl
          mountPath: /dev/nvidiactl
        - name: nvidia-uvm
          mountPath: /dev/nvidia-uvm
        - name: nvidia-modeset
          mountPath: /dev/nvidia-modeset
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
            nvidia.com/gpu: 1  # Request 1 GPU using GPU Operator resource management
          requests:
            cpu: "2"
            memory: "4Gi"
            nvidia.com/gpu: 1  # Request 1 GPU using GPU Operator resource management
        command: ["python3", "/app/spark1_app.py"]
      volumes:
      - name: nvidia-dev
        hostPath:
          path: /dev/nvidia0
      - name: nvidia-ctl
        hostPath:
          path: /dev/nvidiactl
      - name: nvidia-uvm
        hostPath:
          path: /dev/nvidia-uvm
      - name: nvidia-modeset
        hostPath:
          path: /dev/nvidia-modeset