apiVersion: batch/v1
kind: Job
metadata:
  name: spark1
  labels:
    app: spark1
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: spark1
    spec:
      runtimeClassName: nvidia  # Uses the NVIDIA Container Runtime
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - spark1
      securityContext:
        runAsUser: 0            # Runs as root user inside the container
      containers:
      - name: spark1
        image: 192.168.1.150:30500/spark1:latest
        imagePullPolicy: "Always"
        securityContext:
          privileged: true         # Required for GPU device access on Jetson
        env:
          - name: GPU_ENABLED
            value: "true"
          - name: SKIP_DB_CHECK
            value: "true"
        resources:
          limits:
            cpu: "20"
            memory: "119Gi"
          requests:
            cpu: "16"
            memory: "96Gi"
        volumeMounts:
          - name: nvidia0
            mountPath: /dev/nvidia0
          - name: nvidiactl
            mountPath: /dev/nvidiactl
          - name: nvidia-uvm
            mountPath: /dev/nvidia-uvm
          - name: nvidia-modeset
            mountPath: /dev/nvidia-modeset
        command: ["python3", "/app/spark1_app.py"]
      volumes:
        - name: nvidia0
          hostPath:
            path: /dev/nvidia0
        - name: nvidiactl
          hostPath:
            path: /dev/nvidiactl
        - name: nvidia-uvm
          hostPath:
            path: /dev/nvidia-uvm
        - name: nvidia-modeset
          hostPath:
            path: /dev/nvidia-modeset